spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springbd
    username: sa
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug